sudo: true
language: c
compiler:
    - gcc
    - clang
env:
    global:
        - LIBSODIUM_VER=1.0.11
        - MBEDTLS_VER=2.4.0
before_install:
    - wget https://github.com/jedisct1/libsodium/releases/download/1.0.11/libsodium-$LIBSODIUM_VER.tar.gz
    - tar xvf libsodium-$LIBSODIUM_VER.tar.gz
    - pushd libsodium-$LIBSODIUM_VER
    - ./configure --prefix=/usr && make
    - sudo make install
    - popd
    - wget https://tls.mbed.org/download/mbedtls-$MBEDTLS_VER-gpl.tgz
    - tar xvf mbedtls-$MBEDTLS_VER-gpl.tgz
    - pushd mbedtls-$MBEDTLS_VER
    - make
    - sudo make install
    - popd
addons:
    apt:
        packages:
            - autoconf
            - autotools-dev
            - libudns-dev
            - libev-dev
            - asciidoc
            - xmlto
script:
    - ./autogen.sh
    - ./configure && make
branches:
    only:
        - master
notifications:
    recipients:
        - max.c.lv@gmail.com
    email:
        on_success: change
        on_failure: always
